
// const a = require('@/assets/img/ali-pay.png')
// console.log('a', a)

export const loadAssets = (pathFile: string) => {

  // return pathFile.replace('@/assets', 'http://192.168.0.48:5000')
  return pathFile.replace('@/assets', ASSET_CDN)

  // return process.env.NODE_ENV === 'development' ? require(pathFile) : pathFile.replace('@/assets', 'http://192.168.0.48:5000')
}

export const BWYD_ICON = 'https://tsla.bowuyoudao.com/weapp/img/bw_icon.jpg'

export const ALI_PAY_ICON = loadAssets('@/assets/img/ali-pay.png')
export const WX_PAY_ICON = loadAssets('@/assets/img/wx-pay.png')
export const NO_GOODS = loadAssets('@/assets/img/auction-empty.png')
export const NO_CANPAI = loadAssets('@/assets/img/wucanpai.png')
export const STORE_HEADER = loadAssets('@/assets/img/storeHeader.png')
export const YE_PAY_ICON = loadAssets('@/assets/img/ye.png')
export const VIP = loadAssets('@/assets/img/vip.png')
export const EARN = loadAssets('@/assets/img/earn.png')
export const AUTH = loadAssets('@/assets/img/auth.png')
export const POSTER = loadAssets('@/assets/img/poster.png')
export const checkedImg = loadAssets('@/assets/img/duoxuan.png')
export const nocheckedImg = loadAssets('@/assets/img/duoxuan.1.png')
export const SHARE = loadAssets('@/assets/img/shareDemo.png')
export const POINT = loadAssets('@/assets/img/point.png')

export const head = loadAssets('@/assets/img/miaosha.png')
export const start1 = loadAssets('@/assets/img/star1.png')
export const start2 = loadAssets('@/assets/img/star2.png')

export const shouye0 = loadAssets('@/assets/img/shouye0.png')
export const YE = loadAssets('@/assets/img/ye.png')
export const shouye1 = loadAssets('@/assets/img/shouye1.png')
export const fenlei0 = loadAssets('@/assets/img/fenlei0.png')
export const fenlei1 = loadAssets('@/assets/img/fenlei1.png')
export const shangjia0 = loadAssets('@/assets/img/shangjia0.png')
export const shangjia1 = loadAssets('@/assets/img/shangjia1.png')
export const wode0 = loadAssets('@/assets/img/wode0.png')
export const wode1 = loadAssets('@/assets/img/wode1.png')

export const zhuanke = loadAssets('@/assets/img/zhuanke.png')

export const vip1 = loadAssets('@/assets/img/vip1.png')
export const lingxian = loadAssets('@/assets/img/lingxian.png')
export const chuju = loadAssets('@/assets/img/chuju.png')
export const ewm = loadAssets('@/assets/img/ewm.png')

export const siliao = loadAssets('@/assets/img/siliao.png')
export const dianp = loadAssets('@/assets/img/dianp.png')
export const next = loadAssets('@/assets/img/next.png')
export const chujia = loadAssets('@/assets/img/chujia.png')
export const shangp = loadAssets('@/assets/img/shangp.png')
export const zhif = loadAssets('@/assets/img/zhif.png')
export const lingx = loadAssets('@/assets/img/lingx.png')
export const storeHeader = loadAssets('@/assets/img/storeHeader.png')
export const shoucang1 = loadAssets('@/assets/img/shoucang1.png')
export const shoucang0 = loadAssets('@/assets/img/shoucang0.png')
export const success = loadAssets('@/assets/img/success.png')

// import {  } from '@/constants/images'

export const logo = loadAssets('@/assets/img/logo.png')
export const spreadLogo = loadAssets('@/assets/img/spreadLogo.png')
export const slog = loadAssets('@/assets/img/slog.png')

export const tixing = loadAssets('@/assets/img/tixing@2x (1).png')

export const deletePic = loadAssets('@/assets/img/delete.png')

export const card1 = loadAssets('@/assets/img/card1.png')
export const card2 = loadAssets('@/assets/img/card2.png')
export const card3 = loadAssets('@/assets/img/card3.png')
export const cardBorder = loadAssets('@/assets/img/cardBorder.png')

export const yikoujia_icon = loadAssets('@/assets/img/fbykj@2x.png')
export const fapaimai_icon = loadAssets('@/assets/img/fabpm@2x.png')
export const new_icon = loadAssets('@/assets/img/new@2x.png')
export const kaizhibo_icon = loadAssets('@/assets/img/kaizb@2x.png')
export const DOWN0 = loadAssets('@/assets/img/down0.png')
export const DOWN1 = loadAssets('@/assets/img/down1.png')
export const UP0 = loadAssets('@/assets/img/up0.png')
export const UP1 = loadAssets('@/assets/img/up1.png')
export const weixin = loadAssets('@/assets/img/weixin.png')
export const pengyouquan = loadAssets('@/assets/img/pengyouquan.png')
export const lianjie = loadAssets('@/assets/img/lianjie.png')
export const download = loadAssets('@/assets/img/download.png')
export const goldSeller = loadAssets('@/assets/img/goldSeller.png')
export const diamondSeller = loadAssets('@/assets/img/diamondSeller.png')
export const serviceProviders = loadAssets('@/assets/img/serviceProviders.png')
export const userBg = loadAssets('@/assets/img/userBg.png')
export const yqkd = loadAssets('@/assets/img/yqkd.png')
export const sfsq = loadAssets('@/assets/img/sfsq.png')
export const gryq = loadAssets('@/assets/img/gryq.png')
export const tdgl = loadAssets('@/assets/img/tdgl.png')
export const qianbao = loadAssets('@/assets/img/qianbao.png')
export const zhaq = loadAssets('@/assets/img/zhaq.png')
export const kefu = loadAssets('@/assets/img/kefu.png')
export const xtsz = loadAssets('@/assets/img/xtsz.png')
export const ykjgl = loadAssets('@/assets/img/ykjgl.png')
export const shangxy = loadAssets('@/assets/img/shangxy.png')


export const bianji = loadAssets('@/assets/img/bianji.png')
export const xiajia = loadAssets('@/assets/img/xiajia.png')
export const share = loadAssets('@/assets/img/share.png')
export const paimai = loadAssets('@/assets/img/paimai.png')
export const fenxiang = loadAssets('@/assets/img/fenxiang.png')
export const back = loadAssets('@/assets/img/back.png')
export const poster2 = loadAssets('@/assets/img/poster2.png')
export const empty = loadAssets('@/assets/img/empty.png')

export const addr_border = loadAssets('@/assets/img/addr_border.png')
export const preview = loadAssets('@/assets/img/preview.png')

export const saomiao = loadAssets('@/assets/img/saomiao@2x.png')
export const bowu = loadAssets('@/assets/img/bowu.png')
export const bowub = loadAssets('@/assets/img/bowub.png')
export const fb0 = loadAssets('@/assets/img/fb0.png')
export const fb1 = loadAssets('@/assets/img/fb1.png')
export const rz = loadAssets('@/assets/img/rz.png')
export const mrtx = loadAssets('@/assets/img/mrtx.png')
export const jp = loadAssets('@/assets/img/jp.png')

export const resultAttention = loadAssets('@/assets/img/result-attention.png')

export const bw_icon = loadAssets('@/assets/img/bw_icon.jpg')
export const vip0 = loadAssets('@/assets/img/vip0.png')

export const hjLevel = loadAssets('@/assets/img/huangjLevel.png')
export const zsLevel = loadAssets('@/assets/img/zuansLevel.png')
export const serviceLevel = loadAssets('@/assets/img/fuwsLevel.png')

export const profit = loadAssets('@/assets/img/profit.png')
export const emoj = loadAssets('@/assets/img/emoj.png')
export const plus = loadAssets('@/assets/img/plus.png')
export const tupian = loadAssets('@/assets/img/tupian.png')
export const paishe = loadAssets('@/assets/img/paishe.png')
export const shipin = loadAssets('@/assets/img/shipin.png')
export const open = loadAssets('@/assets/img/open1.png')
export const openStore = loadAssets('@/assets/img/openStoreBg.png')
export const leak = loadAssets('@/assets/img/leak.png')
export const highGoods = loadAssets('@/assets/img/highGoods.png')
export const highGoodsBorder = loadAssets('@/assets/img/highGoodsBorder.png')
export const highGoodsBorder1 = loadAssets('@/assets/img/active_border1.png')
export const highGoodsBorder2 = loadAssets('@/assets/img/active_border2-2.png')
export const newUserShare = loadAssets('@/assets/img/newUserShare.png')
export const buybg = loadAssets('@/assets/img/active_buy_info.png')
export const loading = loadAssets('@/assets/img/loading.png')
export const loading1 = loadAssets('@/assets/img/loading2.png')

export const high_goods = loadAssets('@/assets/img/high_goods.png')
export const active_bottom = loadAssets('@/assets/img/active_bottom.png')
export const new_share_canvas = loadAssets('@/assets/img/new_share_canvas.png')
export const pick_canvas = loadAssets('@/assets/img/pick_canvas.png')
export const wenhao = loadAssets('@/assets/img/wenhao.png')
// export const high_goods = 'https://picsum.photos/id/68/300/300'
// export const active_bottom = 'https://picsum.photos/id/447/261/72'


export const ruzhu = loadAssets('@/assets/img/入驻@2x.png')
export const gouwu = loadAssets('@/assets/img/购物@2x.png')
export const shouhou = loadAssets('@/assets/img/售后@2x.png')
export const caiwu = loadAssets('@/assets/img/财务@2x.png')
export const helpActive = loadAssets('@/assets/img/helpActive.png')

export const xinfen = loadAssets('@/assets/img/onePrice_title.png')
export const shihui = loadAssets('@/assets/img/shihiu_title.png')
export const jingxuan = loadAssets('@/assets/img/jingxuan_title.png')
export const haowu = loadAssets('@/assets/img/baiyuan_title.png')
export const weizhi = loadAssets('@/assets/img/dingwei@2x.png')

export const yyby = loadAssets('@/assets/img/yyby.png')
export const shhw = loadAssets('@/assets/img/shhw.png')
export const yyjp = loadAssets('@/assets/img/yyjp.png')
export const gxjb = loadAssets('@/assets/img/gxjb.png')
export const yjby = loadAssets('@/assets/img/yjby.png')
export const zp = loadAssets('@/assets/img/zp.png')
export const fk = loadAssets('@/assets/img/fk.png')
export const shopping = loadAssets('@/assets/img/shopping.png')

export const kaitongzhibo = loadAssets('@/assets/img/kaitongzhibo.png')
export const cj = loadAssets('@/assets/img/cj.png')
export const leftCloud = loadAssets('@/assets/img/leftCloud.png')
export const rightCloud = loadAssets('@/assets/img/rightCloud.png')
export const sx = loadAssets('@/assets/img/sx.png')
export const cksx = loadAssets('@/assets/img/cksx.png')
export const ckts = loadAssets('@/assets/img/ckts.png')
export const ckxc = loadAssets('@/assets/img/ckxc.png')
export const bdSucess = loadAssets('@/assets/img/bdSucess.png')
export const quxiaoyuzhan = loadAssets('@/assets/img/quxiaoyuzhan@2x.png')
export const lijizhibo = loadAssets('@/assets/img/lijizhibo@2x.png')
export const wyby = loadAssets('@/assets/img/wyby.png')
export const gzlq = loadAssets('@/assets/img/gzlq.png')

// 拉新相关
export const zxj = loadAssets('@/assets/img/zxj.png')
export const lxbg = loadAssets('@/assets/img/lxbg.png')
export const yqgl = loadAssets('@/assets/img/glqt.png')
export const lxla = loadAssets('@/assets/img/lx-lb.png')
export const lxhb = loadAssets("@/assets/img/lx-hb.png")

// 新人专享改版
export const hotSale = loadAssets('@/assets/img/hotSale.png')
export const hostSaleFire = loadAssets('@/assets/img/hotSaleFire.png')
export const hotSaleTop1 = loadAssets('@/assets/img/hotSaleTop1.png')
export const hotSaleTop2 = loadAssets('@/assets/img/hotSaleTop2.png')
export const hotSaleTop3 = loadAssets('@/assets/img/hotSaleTop3.png')
export const zhibogongnengjieshao = loadAssets('@/assets/img/zhibogongnengjieshao@2x.png')
export const zbgl = loadAssets('@/assets/img/zbgl@2x.png')
export const zbspgl = loadAssets('@/assets/img/zbspgl@2x.png')
export const yuzhan = loadAssets('@/assets/img/yuzhan@2x.png')
export const liveBottom = loadAssets('@/assets/img/liveBottom.png')
export const live = loadAssets('@/assets/img/live.png')
export const yuzhan1 = loadAssets('@/assets/img/yuzhan.png')
export const ids = loadAssets('@/assets/img/ID@2x.png')
export const openStore1 = loadAssets('@/assets/img/openStore1.png')
export const openStore2 = loadAssets('@/assets/img/openStore2.png')

// 拉新改版
export const pullNewBg2 = loadAssets('@/assets/img/pullNewbg2.png')
export const moreFree = loadAssets('@/assets/img/lxMoreFree.png')
export const txBg = loadAssets('@/assets/img/lxTxModalBg.png')
export const lxhb2 = loadAssets('@/assets/img/lxhb2.png')
export const wxtsbg = loadAssets('@/assets/img/wxti_img.png')
export const pullNewBg3 = loadAssets('@/assets/img/pullNewBg3.png')

// 红包玩法
export const readPacketBg = loadAssets('@/assets/img/redPacketBg.png')
export const shareRedPacketBg = loadAssets('@/assets/img/shareRedPacketBg.png')
export const redPoster = loadAssets('@/assets/img/redPoster.png')
export const redShareimg = loadAssets('@/assets/img/redShareImg.png')

export const openRed = loadAssets('@/assets/img/openRedPacket.png')
export const redDetailBg = loadAssets('@/assets/img/redDetailBg.png')
// 红包规则
export const redRukou = loadAssets('@/assets/img/rukou.png')
export const createRed = loadAssets('@/assets/img/createRed.png')
export const sendRed = loadAssets('@/assets/img/senRed.png')
export const play = loadAssets('@/assets/img/play.png')
export const reward = loadAssets('@/assets/img/orderReward.png')
export const reward2 = loadAssets('@/assets/img/orderReward2.png')
export const gftz = loadAssets('@/assets/img/gftz@2x.png')
export const jywl = loadAssets('@/assets/img/jywl@2x.png')
export const cpxx = loadAssets('@/assets/img/cpxx@2x.png')
export const openredPacket = loadAssets('@/assets/img/openRedPacket2.png')
export const redPoster2 = loadAssets(`@/assets/img/redPoster2.png?x-oss-process=image/resize,w_520,m_lfit`)
export const cumulativeRewardBg = loadAssets('@/assets/img/accumulativeShareRewardModalBg.png')
export const shareModal = loadAssets('@/assets/img/shareModalbg.png')
export const avatar1 = loadAssets('@/assets/img/avatar1.png')
export const avatar2 = loadAssets('@/assets/img/avatar2.png')
export const avatar3 = loadAssets('@/assets/img/avatar3.png')
export const poster_product_top = loadAssets('@/assets/img/poster_product_top.png')
export const spot1 = loadAssets('@/assets/img/spot1.png')
export const spot2 = loadAssets('@/assets/img/spot2.png')
export const spot3 = loadAssets('@/assets/img/spot3.png')
export const spot4 = loadAssets('@/assets/img/spot4.png')
export const spot5 = loadAssets('@/assets/img/spot5.png')
export const spot6 = loadAssets('@/assets/img/spot6.png')
export const spot7 = loadAssets('@/assets/img/spot7.png')
export const dianzan = loadAssets('@/assets/img/dianzan@2x.png')
export const dianzan1 = loadAssets('@/assets/img/dianzan@1x.png')
export const banner_promote = loadAssets('@/assets/img/banner_promote.png')
export const promote_goods_border = loadAssets('@/assets/img/promote_goods_border.png')
export const promote_baoKuan = loadAssets('@/assets/img/promote_baokuan.png')
export const promote_goods_double_border = loadAssets('@/assets/img/promote_double_border.png')
export const launch_down = loadAssets('@/assets/img/launch_down.png')
export const promote_banner = loadAssets('@/assets/img/promote_bannebr.png')
export const report = loadAssets('@/assets/img/report.png')
export const banner_promote1 = loadAssets('@/assets/img/banner_promote1.png')
export const promote_banner1 = loadAssets('@/assets/img/promote_banner1.png')
export const guideToBrower = loadAssets('@/assets/img/guideToBrower.png')
export const kd_kefu = loadAssets('@/assets/img/kd_kefu.png')
export const openRed_bg = loadAssets('@/assets/img/openRed_bg.png')
export const openRed_open = loadAssets('@/assets/img/openRed_open.png')
export const selectGoodsUserBanner = loadAssets('@/assets/img/selectGoodsUserBanner.png')
export const selectGoodsMerchantBanner = loadAssets('@/assets/img/selectGoodsMerchantBanner.png')
export const openRed_open2 = loadAssets('@/assets/img/red_open2.png')
export const openRed_bg2 = loadAssets('@/assets/img/red_bg2.png')
export const return_tag = loadAssets('@/assets/img/return_tag.png')
export const couponBg = loadAssets('@/assets/img/couponBg.png')
export const redbag = loadAssets('@/assets/img/redbag.png')
export const yishiyong = loadAssets('@/assets/img/yishiyong.png')
export const yiguoqi = loadAssets('@/assets/img/yiguoqi.png')
export const red2liveList = loadAssets('@/assets/img/red2LiveLIst.png')
export const liveBg = loadAssets('@/assets/img/liveBg.png')
export const xiaoxi0 = loadAssets('@/assets/img/xiaoxi0.png')
export const xiaoxi1 = loadAssets('@/assets/img/xiaoxi1.png')
export const liverp = loadAssets('@/assets/img/liverp.png')
export const liveRpBg = loadAssets('@/assets/img/liveRpBg.png')
export const liveRpBg_open = loadAssets('@/assets/img/liveRpBg_open.png')
export const liveClose = loadAssets('@/assets/img/liveClose.png') 
export const putong_red= loadAssets('@/assets/img/pt_red.png')
export const xinren_red = loadAssets('@/assets/img/xr_red.png')
export const pinshouqo_red = loadAssets('@/assets/img/psq_red.png')
export const putongRed = loadAssets('@/assets/img/putong_red.png')
export const pinshouqiRed = loadAssets('@/assets/img/pinshouqi_red.png')
export const xinrenRed = loadAssets('@/assets/img/xinrenRed.png')
export const putong_red1= loadAssets('@/assets/img/pt_red_1.png')
export const xinren_red1 = loadAssets('@/assets/img/xinren_red_1.png')
export const pinshouqo_red1 = loadAssets('@/assets/img/psq_red_1.png')
export const coupons_yijieshu = loadAssets('@/assets/img/yijieshu.png')
export const coupons_yizhongzhi = loadAssets('@/assets/img/yizhongzhi.png')
export const redPoster3 = loadAssets('@/assets/img/redPoster3.png')
export const hbkq_merchant = loadAssets('@/assets/img/hbkq_merchant.png')
export const liverp_p = loadAssets('@/assets/img/liverp_p.png')

